# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\rmessage.proto\"1\n\x05Image\x12\x0c\n\x04rows\x18\x01 \x02(\r\x12\x0c\n\x04\x63ols\x18\x02 \x02(\r\x12\x0c\n\x04\x64\x61ta\x18\x03 \x02(\x0c\"+\n\x0fPixelCoordinate\x12\x0b\n\x03row\x18\x01 \x02(\x02\x12\x0b\n\x03\x63ol\x18\x02 \x02(\x02\"\x82\x01\n\rReqDetections\x12\x15\n\x05image\x18\x01 \x02(\x0b\x32\x06.Image\x12\x1c\n\x0ereturn_heatmap\x18\x02 \x01(\x08:\x04true\x12\x1f\n\x10upsample_heatmap\x18\x03 \x01(\x08:\x05\x66\x61lse\x12\x1b\n\x0creturn_peaks\x18\x04 \x01(\x08:\x05\x66\x61lse\"I\n\rRepDetections\x12\x17\n\x07heatmap\x18\x01 \x01(\x0b\x32\x06.Image\x12\x1f\n\x05peaks\x18\x02 \x03(\x0b\x32\x10.PixelCoordinate\"X\n\x0bReqTracking\x12\x0f\n\x07\x63ontext\x18\x01 \x01(\x0c\x12\x17\n\x07heatmap\x18\x02 \x02(\x0b\x32\x06.Image\x12\x1f\n\x05peaks\x18\x03 \x03(\x0b\x32\x10.PixelCoordinate\"?\n\x05Track\x12$\n\ncoordinate\x18\x01 \x02(\x0b\x32\x10.PixelCoordinate\x12\x10\n\x08track_id\x18\x02 \x02(\r\"6\n\x0bRepTracking\x12\x0f\n\x07\x63ontext\x18\x01 \x02(\t\x12\x16\n\x06tracks\x18\x02 \x03(\x0b\x32\x06.Track\"\\\n\x07Request\x12$\n\ndetections\x18\x01 \x01(\x0b\x32\x0e.ReqDetectionsH\x00\x12 \n\x08tracking\x18\x02 \x01(\x0b\x32\x0c.ReqTrackingH\x00\x42\t\n\x07request')
)




_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rows', full_name='Image.rows', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cols', full_name='Image.cols', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='Image.data', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=66,
)


_PIXELCOORDINATE = _descriptor.Descriptor(
  name='PixelCoordinate',
  full_name='PixelCoordinate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='row', full_name='PixelCoordinate.row', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='col', full_name='PixelCoordinate.col', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=111,
)


_REQDETECTIONS = _descriptor.Descriptor(
  name='ReqDetections',
  full_name='ReqDetections',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='ReqDetections.image', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='return_heatmap', full_name='ReqDetections.return_heatmap', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='upsample_heatmap', full_name='ReqDetections.upsample_heatmap', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='return_peaks', full_name='ReqDetections.return_peaks', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=244,
)


_REPDETECTIONS = _descriptor.Descriptor(
  name='RepDetections',
  full_name='RepDetections',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='heatmap', full_name='RepDetections.heatmap', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='peaks', full_name='RepDetections.peaks', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=319,
)


_REQTRACKING = _descriptor.Descriptor(
  name='ReqTracking',
  full_name='ReqTracking',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='context', full_name='ReqTracking.context', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heatmap', full_name='ReqTracking.heatmap', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='peaks', full_name='ReqTracking.peaks', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=321,
  serialized_end=409,
)


_TRACK = _descriptor.Descriptor(
  name='Track',
  full_name='Track',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='coordinate', full_name='Track.coordinate', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='track_id', full_name='Track.track_id', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=411,
  serialized_end=474,
)


_REPTRACKING = _descriptor.Descriptor(
  name='RepTracking',
  full_name='RepTracking',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='context', full_name='RepTracking.context', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tracks', full_name='RepTracking.tracks', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=476,
  serialized_end=530,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='detections', full_name='Request.detections', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tracking', full_name='Request.tracking', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='request', full_name='Request.request',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=532,
  serialized_end=624,
)

_REQDETECTIONS.fields_by_name['image'].message_type = _IMAGE
_REPDETECTIONS.fields_by_name['heatmap'].message_type = _IMAGE
_REPDETECTIONS.fields_by_name['peaks'].message_type = _PIXELCOORDINATE
_REQTRACKING.fields_by_name['heatmap'].message_type = _IMAGE
_REQTRACKING.fields_by_name['peaks'].message_type = _PIXELCOORDINATE
_TRACK.fields_by_name['coordinate'].message_type = _PIXELCOORDINATE
_REPTRACKING.fields_by_name['tracks'].message_type = _TRACK
_REQUEST.fields_by_name['detections'].message_type = _REQDETECTIONS
_REQUEST.fields_by_name['tracking'].message_type = _REQTRACKING
_REQUEST.oneofs_by_name['request'].fields.append(
  _REQUEST.fields_by_name['detections'])
_REQUEST.fields_by_name['detections'].containing_oneof = _REQUEST.oneofs_by_name['request']
_REQUEST.oneofs_by_name['request'].fields.append(
  _REQUEST.fields_by_name['tracking'])
_REQUEST.fields_by_name['tracking'].containing_oneof = _REQUEST.oneofs_by_name['request']
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['PixelCoordinate'] = _PIXELCOORDINATE
DESCRIPTOR.message_types_by_name['ReqDetections'] = _REQDETECTIONS
DESCRIPTOR.message_types_by_name['RepDetections'] = _REPDETECTIONS
DESCRIPTOR.message_types_by_name['ReqTracking'] = _REQTRACKING
DESCRIPTOR.message_types_by_name['Track'] = _TRACK
DESCRIPTOR.message_types_by_name['RepTracking'] = _REPTRACKING
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), dict(
  DESCRIPTOR = _IMAGE,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:Image)
  ))
_sym_db.RegisterMessage(Image)

PixelCoordinate = _reflection.GeneratedProtocolMessageType('PixelCoordinate', (_message.Message,), dict(
  DESCRIPTOR = _PIXELCOORDINATE,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:PixelCoordinate)
  ))
_sym_db.RegisterMessage(PixelCoordinate)

ReqDetections = _reflection.GeneratedProtocolMessageType('ReqDetections', (_message.Message,), dict(
  DESCRIPTOR = _REQDETECTIONS,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:ReqDetections)
  ))
_sym_db.RegisterMessage(ReqDetections)

RepDetections = _reflection.GeneratedProtocolMessageType('RepDetections', (_message.Message,), dict(
  DESCRIPTOR = _REPDETECTIONS,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:RepDetections)
  ))
_sym_db.RegisterMessage(RepDetections)

ReqTracking = _reflection.GeneratedProtocolMessageType('ReqTracking', (_message.Message,), dict(
  DESCRIPTOR = _REQTRACKING,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:ReqTracking)
  ))
_sym_db.RegisterMessage(ReqTracking)

Track = _reflection.GeneratedProtocolMessageType('Track', (_message.Message,), dict(
  DESCRIPTOR = _TRACK,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:Track)
  ))
_sym_db.RegisterMessage(Track)

RepTracking = _reflection.GeneratedProtocolMessageType('RepTracking', (_message.Message,), dict(
  DESCRIPTOR = _REPTRACKING,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:RepTracking)
  ))
_sym_db.RegisterMessage(RepTracking)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  ))
_sym_db.RegisterMessage(Request)


# @@protoc_insertion_point(module_scope)
